=== tokamak-energy/gsfit/python/gsfit/settings_schema/xsd/equilibrium/constraints_b_field_pol_probe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="constraints__b_field_pol_probe">
        <xs:annotation>
            <xs:documentation>
                Fitting settings for the poloidal magnetic field probes (Mirnov coils), with one `b_field_pol_probe` element per probe.
                A probe read by the `database_reader` which is not listed here is not included in the fit.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="b_field_pol_probe" type="b_field_pol_probe" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            Fitting settings for one probe.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="b_field_pol_probe_name_key">
            <xs:annotation>
                <xs:documentation>
                    Each probe's `name` must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="b_field_pol_probe"/>
            <xs:field xpath="name"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="b_field_pol_probe">
        <xs:sequence>
            <xs:element name="name" type="sensor_name">
                <xs:annotation>
                    <xs:documentation>
                        Name of the probe, e.g. `P101`.
                        Must be unique, and match the name read by the `database_reader`.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="comment" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Free-text comment, e.g. on the quality of the signal; may be empty.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="expected_value" type="finite_double_positive">
                <xs:annotation>
                    <xs:documentation>
                        Expected magnitude of the measurement, used to normalise the measurement.
                    </xs:documentation>
                    <xs:appinfo>
                        <units>tesla</units>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
            <xs:element name="include" type="true_or_false">
                <xs:annotation>
                    <xs:documentation>
                        Whether to include the probe in the fit.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="weight" type="finite_double_non_negative">
                <xs:annotation>
                    <xs:documentation>
                        Relative weight of the probe in the fit.
                    </xs:documentation>
                    <xs:appinfo>
                        <units>dimensionless</units>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="finite_double">
        <xs:annotation>
            <xs:documentation>
                A finite `xs:double`; `NaN`, `INF` and `-INF` are not allowed.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:double">
            <xs:pattern value="[+\-]?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+\-]?[0-9]+)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="finite_double_non_negative">
        <xs:restriction base="finite_double">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="finite_double_positive">
        <xs:restriction base="finite_double">
            <xs:minExclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sensor_name">
        <xs:annotation>
            <xs:documentation>
                A non-empty name without any whitespace.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="\S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="true_or_false">
        <xs:annotation>
            <xs:documentation>
                A boolean written as `true` or `false`; `xs:boolean` alone would also accept `1` and `0`.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:boolean">
            <xs:pattern value="true|false"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== tokamak-energy/gsfit/python/gsfit/settings/st40_P2p3_calibrations_new_xml_schema/equilibrium/constraints_b_field_pol_probe.xml
<?xml version="1.0" encoding="UTF-8"?>
<constraints__b_field_pol_probe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../settings_schema/xsd/equilibrium/constraints_b_field_pol_probe.xsd">
    <b_field_pol_probe>
        <name>P101</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P102</name>
        <comment>very good tf removal, and started with very little tf pickup</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P103</name>
        <comment>non-physical wiggles in TF vacuum shot</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P104</name>
        <comment>ok tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P105</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P106</name>
        <comment>good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P107</name>
        <comment>very good tf removal; under HFSPSRT divertor, bad match</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P108</name>
        <comment>ok tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P109</name>
        <comment>ok tf removal, but a bit non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P110</name>
        <comment>good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P111</name>
        <comment>very good tf removal, but poor dynamic range</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P112</name>
        <comment>very poor tf removal, non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>0.5</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P113</name>
        <comment>good tf removal, started with very low tf pickup; doesnt match other sensors in reconstruction</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P114</name>
        <comment>ok tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P115</name>
        <comment>ok tf removal, started with very low tf pickup</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P116</name>
        <comment>ok tf removal, but a little non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P117</name>
        <comment>ok tf removal, but a little non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P118</name>
        <comment>good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P119</name>
        <comment>very good tf removal; doesn't match other sensors in reconstruction</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P120</name>
        <comment>ok tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P121</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P122</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P123</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P124</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P125</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P126</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P127</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P128</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P129</name>
        <comment>very good tf removal; under HFSPSRB divertor, bad match</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P130</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>false</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P131</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P132</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P133</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P134</name>
        <comment>very good tf removal, and started with very little tf pickup</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P318</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P501</name>
        <comment>very good tf removal</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P502</name>
        <comment>ok tf removal, but a little non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P503</name>
        <comment>ok tf removal, but a bit non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P504</name>
        <comment>ok tf removal, but a bit non-physical</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P505</name>
        <comment>good tf removal, a little non-physical, but started with low tf pickup</comment>
        <expected_value>0.01</expected_value>
        <include>true</include>
        <weight>1.0</weight>
    </b_field_pol_probe>
    <b_field_pol_probe>
        <name>P506</name>
