=== tokamak-energy/gsfit/python/gsfit/settings_schema/xsd/equilibrium/grid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Schema for grid.xml: the (R, Z) grid the equilibrium is solved on, and the psi_n grid of the 1D profiles.

    See ../GSFIT_code_settings.xsd for the conventions shared by all the schemas.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

    <!-- ================================= Other simple types ================================= -->

    <xs:simpleType name="PositiveDouble">
        <xs:annotation><xs:documentation>A number greater than 0</xs:documentation></xs:annotation>
        <xs:restriction base="xs:double">
            <xs:minExclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ================================= The settings file ================================= -->

    <xs:element name="grid">
        <xs:annotation><xs:documentation>The (R, Z) grid the equilibrium is solved on, and the psi_n grid of the 1D profiles</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="n_r" type="xs:nonNegativeInteger">
                    <xs:annotation><xs:documentation>Number of radial grid points</xs:documentation></xs:annotation>
                </xs:element>
                <xs:element name="n_z" type="xs:nonNegativeInteger">
                    <xs:annotation><xs:documentation>Number of vertical grid points</xs:documentation></xs:annotation>
                </xs:element>
                <xs:element name="r_min" type="PositiveDouble">
                    <xs:annotation>
                        <xs:documentation>Minimum major radius</xs:documentation>
                        <xs:appinfo>
                            <units>m</units>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="r_max" type="PositiveDouble">
                    <xs:annotation>
                        <xs:documentation>Maximum major radius</xs:documentation>
                        <xs:appinfo>
                            <units>m</units>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="z_min" type="xs:double">
                    <xs:annotation>
                        <xs:documentation>Minimum vertical position</xs:documentation>
                        <xs:appinfo>
                            <units>m</units>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="z_max" type="xs:double">
                    <xs:annotation>
                        <xs:documentation>Maximum vertical position</xs:documentation>
                        <xs:appinfo>
                            <units>m</units>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="n_psi_n" type="xs:nonNegativeInteger">
                    <xs:annotation><xs:documentation>Number of points in the normalised poloidal flux, psi_n, evenly spaced from 0 (magnetic axis) to 1 (boundary), on which the 1D profiles are given</xs:documentation></xs:annotation>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tokamak-energy/gsfit/python/gsfit/settings/st40_P2p3_calibrations_new_xml_schema/equilibrium/grid.xml
<?xml version="1.0" encoding="UTF-8"?>
<grid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../settings_schema/xsd/equilibrium/grid.xsd">
    <n_r>81</n_r>
    <n_z>161</n_z>
    <r_min>0.01</r_min>
    <r_max>1.01</r_max>
    <z_min>-1.0</z_min>
    <z_max>1.0</z_max>
    <n_psi_n>100</n_psi_n>
</grid>
