=== tokamak-energy/gsfit/python/gsfit/settings_schema/xsd/equilibrium/timeslices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Schema for timeslices.xml: the times GSFit reconstructs.

    See ../GSFIT_code_settings.xsd for the conventions shared by all the schemas.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

    <!-- ===================================== Enums ===================================== -->

    <xs:simpleType name="TimeslicesMethod">
        <xs:annotation>
            <xs:documentation>
                The ways of choosing the times to reconstruct, from `Gsfit.setup_timeslices` in python/gsfit/gsfit.py
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="arange">
                <xs:annotation>
                    <xs:documentation>
                        Evenly spaced times
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="linspace">
                <xs:annotation>
                    <xs:documentation>
                        Evenly spaced times
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="user_defined">
                <xs:annotation>
                    <xs:documentation>
                        A list of times
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="good_pressure_sensors">
                <xs:annotation>
                    <xs:documentation>
                        The times at which the pressure sensors are good (BAD_MA is false in the PPTS tree), for ST40's experimental MDSplus database. It has no settings: the PPTS run is `ppts` in thomson_scattering.xml, in the element of the database reader in use
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <!-- ================================= Other simple types ================================= -->

    <xs:simpleType name="FiniteDouble">
        <xs:annotation>
            <xs:documentation>
                A finite `xs:double`; `NaN`, `INF` and `-INF` are not allowed.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:double">
            <xs:pattern value="[+\-]?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+\-]?[0-9]+)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FinitePositiveDouble">
        <xs:annotation>
            <xs:documentation>
                A finite number greater than 0.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="FiniteDouble">
            <xs:minExclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FiniteDoubleList">
        <xs:annotation>
            <xs:documentation>
                A list of finite numbers, written space-separated, e.g. "0.1 0.2 0.3".
            </xs:documentation>
        </xs:annotation>
        <xs:list itemType="FiniteDouble"/>
    </xs:simpleType>

    <!-- ================================= The settings file ================================= -->

    <xs:element name="timeslices">
        <xs:annotation>
            <xs:documentation>
                The times to reconstruct
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="method" type="TimeslicesMethod">
                    <xs:annotation>
                        <xs:documentation>
                            How the times are chosen. Its settings are in the element of the same name, below
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="arange">
                    <xs:annotation>
                        <xs:documentation>
                            Times from time_start, in steps of dt, up to but not including time_end (numpy.arange)
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="time_start" type="FiniteDouble">
                                <xs:annotation>
                                    <xs:documentation>
                                        First time
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <units>second</units>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="time_end" type="FiniteDouble">
                                <xs:annotation>
                                    <xs:documentation>
                                        End of the times, which is not included
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <units>second</units>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="dt" type="FinitePositiveDouble">
                                <xs:annotation>
                                    <xs:documentation>
                                        Step between times
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <units>second</units>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="linspace">
                    <xs:annotation>
                        <xs:documentation>
                            n_time evenly spaced times, from time_start to time_end, both included (numpy.linspace)
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="time_start" type="FiniteDouble">
                                <xs:annotation>
                                    <xs:documentation>
                                        First time
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <units>second</units>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="time_end" type="FiniteDouble">
                                <xs:annotation>
                                    <xs:documentation>
                                        Last time
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <units>second</units>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="n_time" type="xs:nonNegativeInteger">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of times
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="user_defined" type="FiniteDoubleList">
                    <xs:annotation>
                        <xs:documentation>
                            User defined time-slices, space-separated list, e.g. "80.e-3 100.0e-3 120.0e-3"
                        </xs:documentation>
                        <xs:appinfo>
                            <units>second</units>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tokamak-energy/gsfit/python/gsfit/settings/st40_P2p3_calibrations_new_xml_schema/equilibrium/timeslices.xml
<?xml version="1.0" encoding="UTF-8"?>
<timeslices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../settings_schema/xsd/equilibrium/timeslices.xsd">
    <method>arange</method>
    <arange>
        <time_start>10.0e-3</time_start>
        <time_end>250.0e-3</time_end>
        <dt>0.5e-3</dt>
    </arange>
    <linspace>
        <time_start>5.0e-3</time_start>
        <time_end>250.0e-3</time_end>
        <n_time>20</n_time>
    </linspace>
    <user_defined>80.0e-3 100.0e-3 120.0e-3</user_defined>
</timeslices>
